### ISSUE TITLE
PATO namespace

### ISSUE THREAD

**Issue by saralafia** [pato-ontology/pato#102]
The PATO namespace
[http://purl.obolibrary.org/obo/pato#](url)
redirects to 
[https://github.com/pato-phenotype/pato#](url)
which is broken. Is it supposed to point to
[http://www.berkeleybop.org/ontologies/pato/](url)
? Thanks!

**Comment by cmungall** [comment]
Where did you come across that URL?

the class PURLs should be

http://purl.obolibrary.org/obo/PATO_nnnnnnnn

The ontology PURLs are

http://purl.obolibrary.org/obo/pato.{obo,owl}

There should be no hash-based PURLs

**Comment by saralafia** [comment]
When I imported PATO using Protege, this is the namespace. I've attached my owl file and the import shows on (line 16) - apologies if this goes beyond your scope (if it's an import issue).
[d1-ECSO.owl.zip](https://github.com/pato-ontology/pato/files/468517/d1-ECSO.owl.zip)

**Comment by cmungall** [comment]
Thanks for the attachment, I understand the issue now.

It looks like the maintainers of ESCO (is that you?) need to remove line 16. It's actually harmless (namespace declarations in RDF/XML don't have any meaning they are there just for the convenience of shortening URLs). However, it's potentially confusing as (1) it is never actually used as a QNAME in the ESCO file (2) it doesn't correspond to any URL prefix officially used by the PATO ontology (at least not deliberately, it's possible we are somehow indirectly at fault here)

**Comment by cmungall** [comment]
Unrelated to namespaces, but dataone users may have an opinion on this ticket: #101

**Comment by saralafia** [comment]
Thanks! I removed the line but the issue isn't resolved so I think the problem is on my end with the PATO import. I really appreciate the quick help.

**Comment by cmungall** [comment]
Ah yes, it's from PATO_import.owl in sem-prov-ontologies/observation

however, I see the actual issue is on the PATO end, or rather on the OBO/OWL translation end.

The official PURLs for PATO subsets are of the form http://purl.obolibrary.org/obo/pato#value_slim

These don't resolve to anything about the subset itself. I have fixed the PURLs so at least http://purl.obolibrary.org/obo/pato resolves to the home page on github. I may be able to put in # anchors for some of the subsets.

But ultimately hash PURLs are bad, but for various reasons it would be too hard to fix these now. 

dataone may want to consider stripping some annotations, I doubt the subsets are useful to you

**Comment by shawntanzk** [comment]
Hopefully this is resolved now? since it's from 2016 I'm going to close this, but please do reopen and place it in https://github.com/orgs/obophenotype/projects/5 if this is still a problem that needs to be fixed. Thanks
