### ISSUE TITLE
pathogenicity

### ISSUE THREAD

**Issue by ValWood** [pato-ontology/pato#144]
Hi,

I am working with PHIBase http://www.phi-base.org/ to formalise their  Pathogen-host interaction phenotypes.

We  require a PATO qualifier for  "pathogenicity" ("pathogenicity phenotype" will be one of our high level terms)

Definition
The ability of a pathogen to produce an infectious disease or disorder in an another organism.

(its a fairly standard def, so I don't know what to cite as the source)

Let me know if you need any further information.

Thanks
Val

**Comment by mah11** [comment]
Note that the definition of the existing 'virulence' term should also change.

id: PATO:0002146
name: virulence
def: "A quality inhering in a bearer by virtue of the bearer's pathogenicity." [PATOC:GVG]

On advice from PHI-Base folk, we suggest:

"A quality inhering in a bearer by virtue of the severity of disease caused by the bearer in a target organism."

As they explained it, pathogenicity is binary - an organism either is or isn't pathogenic. Virulence is a continuously varying quality of a pathogen, and describes howe severe a disease the pathogen causes.

**Comment by nicolevasilevsky** [comment]
I added this new class and updated the def.
@ValWood I added your ORCID for the new term and @mah11 I added your ORCID (and mine) for the new def.

**Comment by ValWood** [comment]
Thanks Nicole,
The ORCID for the def should be  @CuzickA  (term and Def). M and I were chanelling.:)
cheers
val

**Comment by ValWood** [comment]
https://orcid.org/0000-0001-8941-3984

**Comment by nicolevasilevsky** [comment]
I updated the xref, thanks @ValWood!

**Comment by CuzickA** [comment]
Many thanks for the above.

**Comment by ValWood** [comment]
Hi 
We can't see these changes. Could they be merged  in ?
Cheers,
v

**Comment by nicolevasilevsky** [comment]
@ValWood, you should be able see the changes now.

**Comment by ValWood** [comment]
Thanks, I saw the commit we will check soon.
Val

**Comment by CuzickA** [comment]
I can now see the new 'pathogenicity' term and change to the 'virulence' term in PATO thank you. 

Please could you add my orcid (above) to the new 'pathogenicity' term @nicolevasilevsky 

Many thanks,
Alayne
