### ISSUE TITLE
Why is this repo not in obo-phenotype?

### ISSUE THREAD

**Issue by drseb** [pato-ontology/pato#334]
Maybe consider moving this repo https://github.com/obophenotype ...

**Comment by matentzn** [comment]
You are right that it could be in obophenotype, but I would be weary to change the location at this stage for a more or less cosmetic reason. First of all, there are non phenotype ontologies using PATO, I think environmental ones for example (don’t know top of my head but I remember seeing PATO classes in surprising places). But most importantly, there might be pipelines that reference raw files in this repo that might not like the automatic redirection. I would say it like this: if there was a good, non-stylistic reason, I would consider it as well, but otherwise the marginal gain is in my opinion not high enough. What do you thing Seb?

**Comment by drseb** [comment]
I see. Makes sense!
