### ISSUE TITLE
Add neuronal morphology quality with common neuronal morphology terms underneath

### ISSUE THREAD

**Issue by dosumis** [pato-ontology/pato#344]
General shape terms are not specific enough.  e.g. for pyramidal neurons, the shape refers to the soma, not the whole cell, and their are other attributes - such as the number an location of projections, which go along with it.

Some subtypes:

 - pyramidal neuronal morphology:
- stellate neuronal morphology
- bipolar neuronal morphology
- pseudobipolar  neuronal morphology

**Comment by dosumis** [comment]
[NPO](https://raw.githubusercontent.com/SciCrunch/NIF-Ontology/neurons/ttl/npo.ttl) already has hierarchy:

![image](https://user-images.githubusercontent.com/112839/94449823-6bd02700-01a4-11eb-8187-70c46e7c2ccc.png)

No text defs though

**Comment by dosumis** [comment]
CC @tbugs.  I'd like to add your Neuron morphological phenotype terms to PATO, prioritising terms that are needed for the Brain Data Standards project.  We'll need text defs and refs though, so we may need to add gradually.

**Comment by dosumis** [comment]
- [ ] @dosumis to create parent class in PATO
- [ ] @shawntanzk to list the morphologies we need for current DBS project work on this ticket
- [ ] @shawntanzk start collecting text definitions for morphologies  - use wikipedia & NPO/[interlex](https://scicrunch.org/scicrunch/interlex) = recording xrefs.

e.g. pyramidal https://en.wikipedia.org/wiki/Pyramidal_cell#Structure - has text : "One of the main structural features of the pyramidal neuron is the conic shaped soma, or cell body, after which the neuron is named. Other key structural features of the pyramidal cell are a single axon, a large apical dendrite, multiple basal dendrites, and the presence of dendritic spines."

**Comment by tgbugs** [comment]
I have another pass on the NPO planned in the next week or two and will update the definitions for morphological phenotypes when I do that. One thing to consider is whether these are dispositions are qualities. I have tended to model many or most of the phenotypes as dispositions since they depend on a particular environment, but morphology seems like it is closer to a quality.

**Comment by patrick-lloyd-ray** [comment]
IMO, morphologies should be qualities (in the BFO sense). Dispositions require realization processes, but morphologies do not, hence are not dispositions. 

I'm open to being shown wrong on this, of course.

**Comment by tgbugs** [comment]
The process of axonal growth and pruning realizes the morphology of a neuronal axonal arbour during development. The problem we run into is whether a cell with the same nucleus but without the axonal morphology is of the same type as the fully developed version, and if not, then how to ensure that different types are compatible if they come from different time points.

**Comment by patrick-lloyd-ray** [comment]
I wouldn't say that the process of axonal growth and pruning realizes the morphology but rather that the cell participates in some process and later comes to have that quality (morphology). Shapes and morphologies are canonical qualities because there's no corresponding realization process for them. Dispositions are internally-grounded realizable entities -- they are a reflection of the physical constitution of the material entity in which they inhere. Part of this are the qualities of that material entity (shape, mass, etc.)

A problem with thinking of morphologies as dispositions is that dispositions are had no matter if they are realized or not (e.g., solubility), so you would end up saying that these cells have this morphology (shape) even if it is not realized (which strikes me as counterintuitive). We'd also have to deal with triggering conditions, etc., for morphologies if they were dispositions. I don't know what a triggering condition for a morphology would be.

Cells can gain and lose qualities (and dispositions) over time and retain their identity, just as humans can gain/lose mass over time and retain their identity. We might end up having to say that cells have [morphology x] at [t1] and [morphology y] at [t2], where x and y are distinct. It would just then be that morphology is not an essential characteristic of the cell at all times.

**Comment by tgbugs** [comment]
Hrm, I think this can work it is the "and later comes to have that quality" that trips me up, I tend to assume that if something bears a quality then it must have always had that quality, but this doesn't have to be the case because we haven't specified how we are dealing with time, e.g. that we have to qualify certain qualities so that they are only restricted to the fully developed state as you suggest.

The triggering conditions for morphology are things like being in the right place in the brain with the right signalling molecules and the right target molecules present. The conditions are often quite complex, but the simplest example would be that you can take undeveloped neuronal precursors, and put them in a dish, and nothing will happen, if you add the right signalling molecule they will start sending out axons, very much in the same way that a "bursting" neuron will only show its bursting behaviour if it receives the proper electrical current pulse (or the naturalistic equivalent). One issue there though is that once that phase of development is over and the disposition is realized then looses the disposition and attains a quality. Can you have a disposition to come to bear some quality under the right conditions?

**Comment by patrick-lloyd-ray** [comment]
I think (in BFO terms), the bursting you mention is a disposition (the neuron has those dispositional firing properties due to its physical make-up, and only fires under the right conditions), the process of putting neuronal precursors in a dish and adding the right signaling molecules realizes some dispositions too (the disposition of the precursors to send out axons, etc.), and the morphology of the cell at any time is a quality. I think it's important to note that a cell will always have a shape quality at all times it exists, but it doesn't have to be the same shape quality. E.g., I have a mass quality at all times I exist, but it doesn't have to be the same mass quality.

There might be some disposition of the cell to have that morphology/shape (like a spring has a disposition to extend), but the quality is not the disposition -- which is what I think you are saying in your last sentence. I think we are in agreement AND it's more complicated than it initially seems. 

Maybe it goes like this: cell undergoes process that realizes some disposition -> gains/loses quality maybe as a result of the process -> physical changes (may) lead to new dispositions. 

FWIW, I think that dispositions are more prevalent than most BFO users think -- so I am partial to this line of thought, I just don't think it's right for annotating these classes (yet).

**Comment by tgbugs** [comment]
I think I get it now. I think we are in agreement as well. If we treat the shape of the named thing as a dimension of that named thing then the particular shape or morphology can vary, the morphological phenotypes are then categories of shapes. The disposition related to bursting falls below the level of abstraction of the neuron in question, but in fact do represent a change in change in shape in the underlying constituent parts (ion channels) in response to a change in environment (the strength of the electrical potential across the cell membrane), perhaps the key difference is that the change in shape of the ion channel is reversible in the way the morphology usually isn't (though there are cases where morphology can change and then return, but that might fall outside the traditional understanding of morphology, which is indeed more stable over time).

**Comment by dosumis** [comment]
Wow - some heavy upper ontology argument going on here.

I agree that shape is a quality - although by depositing in PATO under morphology we're only specifying that it is some type of realisable (broader than BFO quality).  

The time issue is a hard one for any modelling in OWL - one which we're definitely not solving here.  In this particular case, I think it's sufficient to track identity over development using lineage relationships. A cell retains its identity but instantiates a new class when it gains pyramidal morphology during differentiation.  We can't track that identity in OWL as a single OWL individual.

On a more practical note:  @tgbugs - would you be happy to switch to using PATO for cell shape phenotype terms, just as you use Uberon for anatomy?  If so, could you work with @shawntanzk on definitions?  Having a shared location for these terms would be great for integration of NPO with the work going on in CL - with the aim of building a common knowledge-base.

**Comment by patrick-lloyd-ray** [comment]
@dosumis The lineage relationship solution seems like a good one to me for this case.

@tgbugs @shawntanzk I can help with this work too, if you need. Feel free to reach out.

**Comment by tgbugs** [comment]
@dosumis Yes, I would be very happy to have a common place where we can maintain all the different cell shapes and PATO is the logical choice. One note is that the way that I had done this was to have overall cell morphology which was some unspecified conflation of axonal morphology, dendritic morphology, and soma morphology. I did this so that it would be possible to use e.g. pyramidal morphological phenotype to cover the more nebulous way that researchers identify neuron morphology.

The reason I did this was because it is useful to be able to have a direct relationship between a cell (neuron in our case) and a quality of one of its parts without having to materialize all the parts. I suspect that this is likely to be a fairly neuron specific modelling need, but if we can get all of those into PATO it would be great.

**Comment by shawntanzk** [comment]
Thanks all for helping out with this! I'm not sure what the best way to approach working on this collaboratively would be, but for now, I'll work on getting a list of morphological features that I've mentioned in descriptions of cell types I'm working on, and maybe we can work from there.

**Comment by dosumis** [comment]
> cell morphology which was some unspecified conflation of axonal morphology, dendritic morphology, and soma morphology

That's the conclusion I'd come to as well.

@tgbugs Can you point @shawntanzk to some text definitions in NPO we could use as a starting point?

**Comment by dosumis** [comment]
@patrick-lloyd-ray @tgbugs - I've given both of you editor permissions on the repo.  
@shawntanzk  - maybe assign the three of us as potential reviewers on PRs & merge to require 1 positive review.

**Comment by shawntanzk** [comment]
I've made a list of cell phenotype, and will start working on it: https://docs.google.com/spreadsheets/d/1PUnVe5EgyKzeDGukrh00y-Jna91HC8be_jXdXCxdYMs/edit?usp=sharing

I'm just getting descriptions from papers now, but will later try to fit some shapes that are already in PATO. 
I'm also not sure where to access NPO which seems to have all the cells we need already - might make life a bit easier. 

As always, any comments will be much appreciated :) 

Thanks!

**Comment by patrick-lloyd-ray** [comment]
I believe the BioRxiv paper for the NPO is: https://www.biorxiv.org/content/10.1101/2020.09.01.278879v1.full which has links to the various versions of NPO.

**Comment by dosumis** [comment]
There's also a link to NPO upthread.  The phenotype terms themselves appear to lack txt defs, but Tom suggested looking at the definitions of corresponding neurons.

**Comment by shawntanzk** [comment]
@dosumis @patrick-lloyd-ray @tgbugs I've written up all the shapes of cells in this[ google sheet](https://docs.google.com/spreadsheets/d/1PUnVe5EgyKzeDGukrh00y-Jna91HC8be_jXdXCxdYMs/edit?usp=sharing) - I've only written up for cell phenotype kind of things (eg basket cell, pyramidal cell etc.) but not properties (eg multipolar dendrites). Happy to add properties but I think that might be something we do as we add in descriptions so we can sort of annotate them? Let me know if you want me to also write up properties too.

Do let me know if you want me to write up tickets for all these on PATO and we can workshop them on tickets if that is preferable? 

Thanks

**Comment by dosumis** [comment]
Suggested text definition pattern, consistent with PATO here: https://github.com/pato-ontology/pato/issues/364#issuecomment-767475535

**Comment by shawntanzk** [comment]
Just realised I've not written an update here: 
I've edited the google sheet to the pattern consistent with PATO (at least I think I did - hopefully they are alright) 
Happy to write up tickets/make pull requests if all is good.

**Comment by shawntanzk** [comment]
Fixed
