### ISSUE TITLE
NTR: pyramidal family morphology

### ISSUE THREAD

**Issue by shawntanzk** [pato-ontology/pato#376]
**Term:** 
pyramidal family morphology

**Definition:**
A cell morphology that inheres in neurons which have a pyramidal shaped soma, a single axon, a large apical dendrite and multiple basal dendrites.
doi:10.1016/b978-0-12-369497-3.10004-4

**Parent Class:**
Cell Morphology #364

**Others:**
Pyramidal (Shape): SAO:1465673360, ILX:0109553

**Notes:**
Related to https://github.com/obophenotype/cell-ontology/issues/751

**Comment by tgbugs** [comment]
@dosumis I would appreciate a review of the modelling here, because on review I think that the way I did this originally is not entirely correct, it conflates standard pyramidal morphology with the superclass of the other types, in that it is usually entirely possible to know that a pyramidal neuron is emphatically not a horizontal pyramidal neuron, however as defined right now this is not possible. I think we might need to shuffle labels and add a class for NormalPyramidalPhenotype or something like that.

**Comment by dosumis** [comment]
Not following.  Does this def conflict with that for horizontal pyramidal neurons?  Perhaps in regard to how apical/basal are determined?

**Comment by tgbugs** [comment]
I think the issue is that colloquially `pyramidal neuron` -> `vertical pyramidal phenotype` so if someone just reports `pyramidal phenotype` unqualified then they mean `vertical pyramidal phenotype`. As a result I never created `vertical pyramidal phenotype` because no one ever talks about it that way or would know what it means. We wind up in a situation where ideally the labels would be `pyramidal family morphological phenotype` or something like that (introducing yet another grouping term such as `family` seems like a bad idea here though), and then there would be `pyramidal morphological phenotype` as a subclass of that and disjoint with `horizontal pyramidal morphological phenotype`. Does this make sense?

**Comment by shawntanzk** [comment]
That makes sense, I think your suggestion on having pyramidal family with standard/vertical pyramidal under it sounds like a good solution. I do worry that it might be confusing if we put it as just pyramidal morphology though - perhaps "standard pyramidal morphology" with "vertical pyramidal morphology" as a synonym and description clearly stating the verticality + as you suggest, disjoint with horizontal pyramidal morphology?

**Comment by tgbugs** [comment]
I think that will work. I think that `pyramidal morphology` will need to be a synonym as well since it is by far the most common usage.

**Comment by shawntanzk** [comment]
I've edited this term to be pyramidal family morphology, and have added standard pyramidal morphology accordingly - do let me know if you think the description is alright. Thanks!
