### ISSUE TITLE
Qualities of neurons

### ISSUE THREAD

**Issue by cmungall** [pato-ontology/pato#55]
Nlx has: 

'apical/basal', bipolar, bitufted, multipolar, other, stellate, 'this is a columnar cell without a true dendrite', unipolar

Other than 'other' and the chatty text these should map to shortcut qualities in PATO, some of which can then be axiomatized (e.g similar to the 'multicellular', 'binucleat' pattern) cc @dosumis  @mellybelly

**Comment by cmungall** [comment]
Also for spine density:

http://neurolex.org/wiki/Category-3ASmooth
http://neurolex.org/wiki/Category-3ASparsely_Spiny_Dendrite_Quality
http://neurolex.org/wiki/Category-3ASpiny_Dendrite_Quality
http://neurolex.org/wiki/Category-3ASpiny_high_density
http://neurolex.org/wiki/Category-3ASpiny_low_density

**Comment by shawntanzk** [comment]
Neuron qualities basically fixed
Spine density not yet, will start looking into it

**Comment by shawntanzk** [comment]
Notes:

Will create a class, dendrite quality, under morphology (PATO:0000051), similar to ILX which is under morphological quality

http://neurolex.org/wiki/Category-3ASmooth -> seems to be taken care of by PATO:0000701 (smooth) 

http://neurolex.org/wiki/Category-3ASpiny_high_density 
http://neurolex.org/wiki/Category-3ASpiny_low_density 
-> not sure why this is under quality in ILX instead of dendrite quality given the definition of dendrite quality seems to explicitly include this. I'll put them under dendrite quality
