### ISSUE TITLE
Link "mineralized" to ENVO:'mineral material'

### ISSUE THREAD

**Issue by pbuttigieg** [pato-ontology/pato#73]
Now that `mineral material` exists in ENVO, perhaps `mineralized` could have something more like a logical def?

**Comment by cmungall** [comment]
Should we not go straight to
CHEBI:46662 ! mineral

E.g.

composed-primarily-of?

Then in ENVO classes are defined the same way we have linkage

I am slightly hesitant as I never know what CHEBI means by substance. It inherits a lot from a chemical structure view of the world rather than a realist view

**Comment by cmungall** [comment]
bearer-of some mineralized == composed-primarily-of some mineral

@wdahdul  does this work for bones and other skeletal elements?

**Comment by cmungall** [comment]
@pbuttigieg as an example of what I mean,

```
  is_a ENVO:00010483 ! environmental material
   is_a ENVO:01000256 ! mineral material
    is_a ENVO:01000681 ! salt *** 
 ```

but salt has no connection to mineral in CHEBI

**Comment by wdahdul** [comment]
We use 'ossified' for vertebrate skeletal phenotypes. 
It looks like  'ossified' and 'mineralized' should be related in the ontology (they are siblings of composition).

**Comment by cmungall** [comment]
[UBERON:4000115](http://purl.obolibrary.org/obo/UBERON_4000115) ! mineralized bone tissue

Note the 4xxxxxx - that's a phenoscape one :->
