### ISSUE TITLE
Partially malformed structures

### ISSUE THREAD

**Issue by seger** [pato-ontology/pato#97]
Currently there are 4 sublasses of 'malformed' - anterioralized, dorsalized, posterioralized, and ventralized - whose definitions require complete lack of the opposite structures (e.g. in an anterioralized embryo, there are no posterior structures) where we actually see a range in experimental outcomes in Xenopus with some but not all opposite structures. We would like to request:

```
id: PATO:new
name: partially anterioralized
def: A malformed quality inhering in a bearer by virtue of the bearer's gross morphology containing what are normally anterior structures and missing some but not all of what are normally posterior structures.
PATO:0000646 ! malformed

id: PATO:new
name: partially dorsalized
def: A malformed quality inhering in a bearer by virtue of the bearer's gross morphology containing what are normally dorsal structures and missing some but not all of what are normally ventral structures.
PATO:0000646 ! malformed

id: PATO:new
name: partially posterioralized
def: A malformed quality inhering in a bearer by virtue of the bearer's gross morphology containing what are normally posterior structures and missing some but not all of what are normally anterior structures.
PATO:0000646 ! malformed

id: PATO:new
name: partially ventralized
def: A malformed quality inhering in a bearer by virtue of the bearer's gross morphology containing what are normally ventral structures and missing some but not all of what are normally dorsal structures.
PATO:0000646 ! malformed
```

**Comment by cmungall** [comment]
presumably we'd like to group these

E.g.

 * FOOized: new
    * partially FOOized: new
    * wholly FOOized: existing class, relabeled

?

**Comment by cmungall** [comment]
If I give you an ID range would be you be able to make a pull request?

**Comment by mellybelly** [comment]
reminds me of developmentally absent versus reduced, e.g.
aplastic
vs
hypoplastic
we always needed to express a continuum here


On Jun 13, 2016, at 5:25 PM, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:


presumably we'd like to group these

E.g.

  *   FOOized: new
     *   partially FOOized: new
     *   wholly FOOized: existing class, relabeled

?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/pato-ontology/pato/issues/97#issuecomment-225747868>, or mute the thread<https://github.com/notifications/unsubscribe/AAwn3LCe98AK9w732vTOZCZxe0Ku5AXOks5qLfT_gaJpZM4I01xB>.

Dr. Melissa Haendel

Associate Professor
Ontology Development Group, OHSU Library
www.ohsu.edu/library/ontology<http://www.ohsu.edu/library/ontology>
Department of Medical Informatics and Clinical Epidemiology
Oregon Health & Science University
haendel@ohsu.edu<mailto:haendel@ohsu.edu>
skype: melissa.haendel
503-407-5970
Appointments: Shanez De Silva desilva@ohsu.edu<mailto:desilva@ohsu.edu>

**Comment by seger** [comment]
Yes, I can make a pull request.
